"""Crear tabla PixelCount

Revision ID: be49239e229e
Revises: d0c7b8e4b57c
Create Date: 2025-04-27 15:41:22.639626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be49239e229e'
down_revision = 'd0c7b8e4b57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pixel_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('fichero', sa.String(length=256), nullable=False),
    sa.Column('pixeles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pixel_counts')
    # ### end Alembic commands ###
